name: bookclub_app
description: A Flutter book reader app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # File handling
  file_picker: ^10.3.10
  path_provider: ^2.1.5
  
  # Storage
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  path: ^1.9.1
  
  # EPUB Parsing
  epubx: ^4.0.0
  archive: ^3.6.1
  
  # State management
  provider: ^6.0.5
  
  # Webview for rendering epub content
  flutter_inappwebview: ^6.1.5
  
  # Utils
  uuid: ^4.5.2
  collection: ^1.19.1
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
